#!/bin/bash

# The follwoing will attempt to install all needed packages to run Hyprland
# This is a quick and dirty script there are no error checking
# This script is meant to run on a clean fresh system
#
# Below is a list of the packages that would be installed
# TODO: ADD THE FUCKING LIST

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then
  echo -e "yay was located, moving on.\n"
else
  echo -e "yay was not located.\n"

  read -n1 -rep "Would you like to install yay to continue this install? y/n: " YAYS
  if [[ $YAYS == "Y" || $YAYS == y ]]; then
    mkdir ~/git
    cd ~/git
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -sic
  else
    echo -e "Unable to continue install without yay."
    exit
  fi
fi

### Install all of the above pacakges ####
read -n1 -rep 'Would you like to install the packages? y/n: ' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
  yay -Suy
  yay -S --noconfirm hyprland kitty waybar \
    fuzzel mako nemo \
    ttf-jetbrains-mono-nerd \
    polkit-gnome python-requests \
    grim slurp pamixer brightnessctl gvfs \
    bluez bluez-utils lxappearance xfce4-settings \
    dracula-icons-git xdg-desktop-portal-hyprland \
    vesktop-bin ttf-vista-fonts btop \
    neovim zsh ripgrep \
    jq stow npm \
    unzip noto-fonts noto-fonts-cjk \
    noto-fonts-emoji noto-fonts-extra \
    nerd-fonts cliphist firefox-developer-edition \
    ly apple_cursor spicetify-cli \
    wttrbar geoip hypridle \
    hyprlock swaybg papirus-icon-theme

  systemctl enable ly

  # Start the bluetooth service
  echo -e "Starting the Bluetooth Service...\n"
  sudo systemctl enable --now bluetooth.service
  sleep 2

  # Clean out other portals
  echo -e "Cleaning out conflicting xdg portals...\n"
  yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk
fi

### Set zsh as shell ###
read -n1 -rep 'Would you like to set your shell to ZSH? y,n: ' ZSH
if [[ $ZSH == "Y" || $ZSH == "y" ]]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files? y/n: ' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
  echo -e "Copying config files...\n"

  cp -R ./various/* ~/.config/

  # Various Individual Files
  # zsh:
  cp ./individuals/zsh/heapbytes.zsh-theme ~/.oh-my-zsh/themes
  cp ./individuals/zsh/.zshrc ~/.zshrc

  # vesktop:
  mkdir -p ~/.config/vesktop/themes/
  mkdir -p ~/.config/vesktop/settings/
  cp ./various/vesktop/themes/catppuccin-mocha.theme.css ~/.config/vesktop/themes
  cp ./various/vesktop/settings/settings.json ~/.config/vesktop/settings/

  # icons + cursors:
  mkdir -p ~/.icons/default
  sudo ln -s /usr/share/icons/macOS-BigSur/cursors ~/.icons/default/cursors

  # fuzzel:
  mkdir -p ~/.config/fuzzel
  cp ./various/fuzzel/fuzzel.ini ~/.config/fuzzel/fuzzel.ini

  # nemo:
  gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty

  # Set some files as exacutable
  chmod +x ~/.config/hypr/xdg-portal-hyprland
  chmod +x ~/.config/waybar/scripts/weather.sh

fi

### Script is done ###
echo -e "Script had completed.\n"
read -n1 -rep 'Would you like to start Hyprland now? y/n: ' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
  exec Hyprland
else
  echo -e "You can start Hyprland at any time by typing 'Hyprland'.\n(or you may restart the computer)"
  exit
fi
